export const dom = {
  canvas:           document.getElementById('game'),
  loadingScreen:    document.getElementById('loading-screen'),
  loadingBar:       document.getElementById('loading-bar'),
  loadingAsset:     document.getElementById('loading-asset'),
  flash:            document.getElementById('flash'),
  score:            document.getElementById('score'),
  highScore:        document.getElementById('high-score'),
  scoreDisplay:     document.getElementById('score-display'),
  startScreen:      document.getElementById('start-screen'),
  gameOverScreen:   document.getElementById('game-over-screen'),
  finalScore:       document.getElementById('final-score'),
  newRecord:        document.getElementById('new-record'),
  gameOverBest:     document.getElementById('game-over-best'),
  restartBtn:       document.getElementById('restart-btn'),
  floatContainer:   document.getElementById('float-container'),
  jumpBtn:          document.getElementById('jump-btn'),
  charSelectScreen: document.getElementById('char-select-screen'),
  charPreviewCanvas:document.getElementById('char-preview'),
  charCategory:     document.getElementById('char-category'),
  charName:         document.getElementById('char-name'),
  charPrevBtn:      document.getElementById('char-prev'),
  charNextBtn:      document.getElementById('char-next'),
  charDots:         document.getElementById('char-dots'),
  charConfirmBtn:   document.getElementById('char-confirm'),
};
