export const State = { LOADING: -1, CHAR_SELECT: 5, MENU: 0, PLAYING: 1, GAME_OVER: 2 };

export const gameState = {
  state: State.LOADING,
  score: 0,
  displayScore: 0,
  highScore: parseInt(localStorage.getItem('runner-high') || '0', 10),
  lastMilestone: 0,
  playerVY: 0,
  isGrounded: true,
  currentSpeed: 7,
  spawnTimer: 0,
  jumpQueued: false,
  keys: {},
  restartReady: false,
  nearMissUsed: new Set(),
  modelCache: null,
  obstaclePool: null,
  parallaxLayers: [],
  groundTiles: [],
  groundStrips: [],
  cloudGroup: null,
  groundTileWidth: 1,
  groundTileCount: 0,
  charIndex: 0,
  shake: { intensity: 0, decay: 0.88 },
  timeScale: { value: 1, target: 1, speed: 5 },
  zoomTarget: 60,
  pScale: { x: 1, y: 1, z: 1 },
};
